### PR TITLE
added package names to readme

### PR DESCRIPTION
**Pull request by hellocatfood**

### CODE REVIEW

**Comment by deiv** [comment]
Thanks for the contribution, the README file is very outdated.

I'm the current maintainer of Driftnet package in Debian and in depends section this is what we have:
libpcap-dev, libjpeg-dev, libgif-dev and libpng-dev. Plus libgtk2.0-dev and xutils-dev if the UI is compiled. I dunno on what distribution you are and if the packages names are the same as Debian.

Would you mind to update the pull-request with this provided info ?

Thanks again !

**Comment by hellocatfood** [comment]
On Ubuntu 14.10 the package libpng-dev is libpng12-dev

**Comment by hellocatfood** [comment]
Would it also be ok to reformat it using markdown? would mean changing the file extension of the Readme to .md

**Comment by deiv** [comment]
Hey, that's sounds good to me.

It has one minor problem, if we remove the README file, later, autools will complain that the file is missing. We can't use a symlink (windows doesn't support them :( ), so I see a pair of options:
* Declare the package as foreign (it not conform to the typical gnu standards).
* Making a rule in the makefile to generate it in plaintext from markdown.

Go ahead and later wll see what road to take.

Thanks !

**Comment by deiv** [comment]
@hellocatfood merged thanks !

**Pull request merged**
